name = "chess-web-worker"
main = "src/index.js"
compatibility_date = "2025-09-21"

[build]
command = "npm install"
upload.format = "modules"
upload.node_compat = true

# Khai báo Durable Object
[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

# Khai báo và liên kết với cơ sở dữ liệu D1
[[d1_databases]]
binding = "DB"
database_name = "chess-app-db"
database_id = "f5eb3c11-34ab-4f40-af26-99ac37bb8bb6"

# Biến môi trường
[vars]
JWT_SECRET = "replace-with-a-strong-secret"

# Đã sửa lỗi: Sử dụng `new_sqlite_classes` thay cho `new_classes`
# Điều này giúp Wrangler biết rằng Durable Object được lưu trữ trong D1
[[migrations]]
tag = "v1"
new_sqlite_classes = [ "GameRoom" ]